version: 2
jobs:
  build:
    docker:
      - image: wsmoses/autophase:latest
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: submodules
          command: |
            git submodule sync
            git submodule update --init --recursive

      - run:
          name: Build
          command: ./build.sh

      - run:
          name: Test-clgen
          command: cd test && python3.6 ./clgentest.py
