FROM library/ubuntu:17.04
RUN apt-get update
RUN apt-get install -y --no-install-recommends cmake
RUN apt-get install -y --no-install-recommends build-essential
RUN apt-get install -y --no-install-recommends ssh
RUN apt-get install -y --no-install-recommends git
RUN apt-get install -y --no-install-recommends python3.6-dev
RUN apt-get install -y --no-install-recommends binutils-dev
RUN apt-get install -y --no-install-recommends wget
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key --no-check-certificate | apt-key add -
RUN echo "deb http://apt.llvm.org/zesty/ llvm-toolchain-zesty-5.0 main" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y --no-install-recommends llvm-5.0-runtime libllvm5.0 llvm-5.0-dev clang-5.0 libclang-5.0-dev

