FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

RUN apt-get update
RUN apt-get install -y --no-install-recommends wget ca-certificates

# CUDA paths
ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:/usr/local/cuda/targets/x86_64-linux/lib/stubs/:$LD_LIBRARY_PATH
ENV PATH /usr/local/bin:/usr/local/cuda/bin:$PATH

RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key --no-check-certificate | apt-key add -
RUN echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main" >> /etc/apt/sources.list
RUN apt-get update

RUN apt-get install -y --no-install-recommends cmake build-essential ssh git curl binutils-dev sudo libz-dev unzip ninja-build m4

RUN apt-get install -y --no-install-recommends llvm-5.0 llvm-5.0-runtime libllvm5.0 llvm-5.0-dev clang-5.0 libclang-5.0-dev
#libjsoncpp1 libstdc++-6-dev libgcc-6-dev libobjc-6-dev libclang1-5.0

RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet --no-check-certificate https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh




#ENV CPLUS_INCLUDE_PATH "/usr/include/python3.6m/"
ENV PATH /opt/conda/bin:$PATH

RUN conda install pytorch torchvision -c pytorch
#RUN conda install pytorch torchvision cuda90 -c pytorch

RUN python -m pip install tensorflow-gpu
RUN apt-get install -y --no-install-recommends libedit-dev

