FROM nvidia/cuda:9.0-devel-ubuntu17.04

RUN echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

ENV CUDNN_VERSION 7.0.3.11
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update

RUN apt install -y --no-install-recommends wget
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key --no-check-certificate | apt-key add -
RUN echo "deb http://apt.llvm.org/zesty/ llvm-toolchain-zesty-5.0 main" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y --no-install-recommends python3.6-dev python3 libpython3.6-dev python3-pip libpython3.6-dev
RUN apt-get install -y llvm-5.0-runtime libllvm5.0 llvm-5.0-dev clang-5.0 libclang-5.0-dev
RUN apt-get install -y llvm-3.9-runtime libllvm3.9 llvm-3.9-dev clang-3.9 libclang-3.9-dev
RUN apt-get install -y --no-install-recommends cmake build-essential ssh git curl binutils-dev sudo libz-dev unzip nvidia-cuda-dev ninja-build

RUN python3.6 -m pip install wheel setuptools --upgrade
ENV CPLUS_INCLUDE_PATH "/usr/include/python3.6m/"


